### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by meztez** [bcgov/climR-pnw#10]
- [x] Document individual R functions
 - [x] ~~Document individual C++~~
 - [ ] Produce beautiful package vignettes that explain how to use package

**Comment by meztez** [comment]
@cmahony start poking around

**Comment by cmahony** [comment]
@meztez great to see the progress. i'm out of commission for the next couple of days, but can have a look on friday. Is there a way for me to test the package yet?

**Comment by meztez** [comment]
@cmahony https://github.com/bcgov/climR-pnw, check README.

**Comment by cmahony** [comment]
@meztez it's tripping up on package 'curl'. i'm troubleshooting it but see below in bold. 

> remotes::install_github("bcgov/climR-pnw")
Downloading GitHub repo bcgov/climR-pnw@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                                  
 2: CRAN packages only                   
 3: None                                 
 4: glue       (1.4.2  -> 1.6.2  ) [CRAN]
 5: Rcpp       (1.0.6  -> 1.0.8.3) [CRAN]
 6: cachem     (1.0.3  -> 1.0.6  ) [CRAN]
 7: cli        (3.0.1  -> 3.2.0  ) [CRAN]
 8: sp         (1.4-5  -> 1.4-6  ) [CRAN]
 9: memoise    (2.0.0  -> 2.0.1  ) [CRAN]
10: gh         (1.2.0  -> 1.3.0  ) [CRAN]
11: data.table (1.13.6 -> 1.14.2 ) [CRAN]
12: ncdf4      (1.17   -> 1.19   ) [CRAN]
13: raster     (3.4-5  -> 3.5-15 ) [CRAN]

Enter one or more numbers, or an empty line to skip updates:1
**curl       (NA     -> 4.3.2  ) [CRAN]**
glue       (1.4.2  -> 1.6.2  ) [CRAN]
Rcpp       (1.0.6  -> 1.0.8.3) [CRAN]
cachem     (1.0.3  -> 1.0.6  ) [CRAN]
cli        (3.0.1  -> 3.2.0  ) [CRAN]
sp         (1.4-5  -> 1.4-6  ) [CRAN]
memoise    (2.0.0  -> 2.0.1  ) [CRAN]
gh         (1.2.0  -> 1.3.0  ) [CRAN]
data.table (1.13.6 -> 1.14.2 ) [CRAN]
ncdf4      (1.17   -> 1.19   ) [CRAN]
raster     (3.4-5  -> 3.5-15 ) [CRAN]
Installing 11 packages: curl, glue, Rcpp, cachem, cli, sp, memoise, gh, data.table, ncdf4, raster
Installing packages into ‘C:/Users/CMAHONY/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/curl_4.3.2.zip'
Content type 'application/zip' length 4322353 bytes (4.1 MB)
downloaded 4.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/glue_1.6.2.zip'
Content type 'application/zip' length 172003 bytes (167 KB)
downloaded 167 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/Rcpp_1.0.8.3.zip'
@meztez I'm troubleshooting a problem with the Package 'curl'. see highlighted lines. 

Content type 'application/zip' length 3355085 bytes (3.2 MB)
downloaded 3.2 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/cachem_1.0.6.zip'
Content type 'application/zip' length 78891 bytes (77 KB)
downloaded 77 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/cli_3.2.0.zip'
Content type 'application/zip' length 1256771 bytes (1.2 MB)
downloaded 1.2 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/sp_1.4-6.zip'
Content type 'application/zip' length 2198811 bytes (2.1 MB)
downloaded 2.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/memoise_2.0.1.zip'
Content type 'application/zip' length 50145 bytes (48 KB)
downloaded 48 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/gh_1.3.0.zip'
Content type 'application/zip' length 141472 bytes (138 KB)
downloaded 138 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/data.table_1.14.2.zip'
Content type 'application/zip' length 2600495 bytes (2.5 MB)
downloaded 2.5 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/ncdf4_1.19.zip'
Content type 'application/zip' length 3271626 bytes (3.1 MB)
downloaded 3.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/raster_3.5-15.zip'
Content type 'application/zip' length 4117613 bytes (3.9 MB)
downloaded 3.9 MB

**package ‘curl’ successfully unpacked and MD5 sums checked
Error: Failed to install 'climRpnw' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘curl’**

**Comment by meztez** [comment]
That's a classic on windows. It fails because remotes is already using curl to download packages. On Windows, packages with C dll object cannot be replaced while they are used, unlike linux.

What I suggest is just installing climRpnw, without updating your existing packages.

You can always do that with update.packages().

**Comment by cmahony** [comment]
roger that. something for documentation.

**Comment by cmahony** [comment]
@meztez 
> # Create a baseline
> normal <- baseline()
> # Select GCM
> gcm <- future(
+   gcm = c("BCC-CSM2-MR", "CanESM5", "IPSL-CM6A-LR"),
+   ssp = c("ssp126", "ssp245"),
+   period = "2041_2060",
+   max_run = 3
+ )
Error in R_nc4_open: Invalid argument
Error in ncdf4::nc_open(filename, readunlim = FALSE, suppress_dimvals = TRUE) : 
  Error in nc_open trying to open file C:\Users\CMAHONY\AppData\Local\R\cache\R\climRpnw\inputs\gcm\BCC-CSM2-MR\gcmData.BCC-CSM2-MR.pr.nc (return_on_error= FALSE )
>

**Comment by meztez** [comment]
That's a classic on windows. It fails because remotes is already using curl to download packages. On Windows, packages with C dll object cannot be replaced while they are used, unlike linux.

What I suggest is just installing climRpnw, without updating your existing packages.

You can always do that with update.packages().

**Comment by meztez** [comment]
> @meztez 
> 
> > > # Create a baseline
> > > normal <- baseline()
> > > # Select GCM
> > > gcm <- future(
> > +   gcm = c("BCC-CSM2-MR", "CanESM5", "IPSL-CM6A-LR"),
> > +   ssp = c("ssp126", "ssp245"),
> > +   period = "2041_2060",
> > +   max_run = 3
> > + )
> > Error in R_nc4_open: Invalid argument
> > Error in ncdf4::nc_open(filename, readunlim = FALSE, suppress_dimvals = TRUE) : 
> >   Error in nc_open trying to open file C:\Users\CMAHONY\AppData\Local\R\cache\R\climRpnw\inputs\gcm\BCC-CSM2-MR\gcmData.BCC-CSM2-MR.pr.nc (return_on_error= FALSE )
> 
> > 

Wondering if there was a hiccup during data_update(). Could you send me a copy the file at the location: C:\Users\CMAHONY\AppData\Local\R\cache\R\climRpnw\inputs\gcm\BCC-CSM2-MR\gcmData.BCC-CSM2-MR.pr.nc

**Comment by cmahony** [comment]
sent by email

**Comment by meztez** [comment]
> sent by email

I was able to reproduce the problem on Windows. Give me a second.

**Comment by meztez** [comment]
@cmahony do a data_delete(), reinstall climRpnw, reload session, load climRpnw and redo data_update(). Sorry for the delays, depending on machine configuration, Windows does not always download file in binary mode. I've explicitly configured it this time.

**Comment by cmahony** [comment]
> data_delete()
Error in winDialog("yesnocancel", msg) : invalid 'message' argument
>

**Comment by meztez** [comment]
@cmahony It works. Still investigating performance issue on Windows.

Also you might get 
```r
Error in x$.self$finalize() : attempt to apply non-function
Error in (function (x)  : attempt to apply non-function
Error in (function (x)  : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
```

These messages can be ignored per terra package maintainer comments. But there are annoying and I'm not done shusing them all.

**Comment by cmahony** [comment]
@meztez wow you are a true magic man. running well and with the test i did it was 25x faster than climateBC. I will send this to Will and Kiri and do a more thorough review on Friday. what is the best way for us to provide you with itemized feedback?

**Comment by meztez** [comment]
@cmahony keep them in a separate. I'm not done with speed up. Most of the time was spent on computing lapse rate. I'm moving that somewhere as the caching does not want to cooperate due to Error mentioned in my previous comment.
