### ISSUE TITLE
Digital elevation model resolution

### ISSUE THREAD

**Issue by meztez** [bcgov/climR-pnw#16]
@cmahony The provided digital elevation model has the same resolution as the target climate variables (tasmin, tasmax and pr). In order to apply the lapse rate adjustment, a better resolution DEM would be best. If I use the provided one, the adjustment would be zero all the time. I could use the same one as the CCISS tool, but if you have access to a better one, even beter. What do you think?

CCISS DEM : 

Digital Elevation Model (DEM) for British Columbia produced by GeoBC. This data is the TRIM DEM converted to the Canadian Digital Elevation Data (CDED) format. The data consists of an ordered array of ground or reflective surface elevations, recorded in metres, at regularly spaced intervals. The spacing of the grid points is .75 arc seconds north/south. The data was converted into 1:50,000 grids for distribution. The scale of this modified data is 1:250,000 which was captured from the original source data which was at a scale of 1:20,000.

**Comment by cmahony** [comment]
no finer dem is required. the user supplies their own dem or simply the elevation of their points of interest. let's have a brief call to discuss. i'll use your calendly.

**Comment by meztez** [comment]
Ever easier! Great

**Comment by cmahony** [comment]
i couldn't find a time that worked for both of us in the next couple of days. but suffice it to be said that the intent is to have the user to supply a csv with id, lat, lon, and elev fields, and then the package will calculate the interpolated and elevation-adjusted values for those points based on the 2km grid and associated lapse rates.

**Comment by meztez** [comment]
I read that, I thought it would have been interesting to pass in an sf points collection then fill the DEM from a database since some users would not be familiar with merging raster over spatial features. Anyway. I'll keep at it.

**Comment by cmahony** [comment]
I'm free to chat now if you are able.

**Comment by cmahony** [comment]
definitely open to creative ideas, so keep that thought as an option for future work.
