### ISSUE TITLE
NaN lapse rate

### ISSUE THREAD

**Issue by meztez** [bcgov/climR-pnw#19]
https://github.com/bcgov/climR-pnw/blob/138d82cc53043bfdf3cc86cbf8e620bae0db75ed/scripts/lapserate.R#L126

Some lapse rate computations will produce NaN as the surrounding cell deltas are all 0s. Instead of NaN, I'm replacing them with 0s, so they won't impact vectorized downscaling. Otherwise, I would have to check for NaN within the loop.

@cmahony Are if you are ok with this hypothesis.

**Comment by cmahony** [comment]
yeah that's fine for now. we can always refine the lapse rate methodology down the road
