### ISSUE TITLE
Feedback on the test version

### ISSUE THREAD

**Issue by cmahony** [bcgov/climR-pnw#29]
@meztez This is a running list of feedback on the test version from Will, Kiri, and Colin. made with the understanding that the package is still in dev and some of these items are already on your mind. 

- [x] some of the derived variables don't show up when requested in downscale() e.g., MAT, MCMT. seems to be the annual ones. 
- [x] temperatures seem to be returned as degrees*10. any reason for this? 
- [x] all months are returned for the basic variables, plus additional requested variables. is there a way to specify only the desired variables? e.g., just Tmax01 and DD5_01. if not, we need this.

**Comment by meztez** [comment]
The variables feature is being worked on. It will do what you think it should do. Will check for temps.

**Comment by cmahony** [comment]
temperatures of -60 and +240 degrees etc.

**Comment by meztez** [comment]
@cmahony How would you like us to compute MAT, Tave, etc.. from Tmin Tmax, PPT any particular recipe you want us to use?

There is no clear mathematical definition for all of them in the paper.

Thanks

**Comment by cmahony** [comment]
@meztez 
- Tave is the average of Tmin and Tmax
- MAT is the average of Tave over all months of year.  
- we need annual and seasonal averages/total for each variable. seasons: winter="wt"=DecJanFeb; spring="sp"=MarAprMay; summer="sm"=JunJulAug; autumn="at"=SepOctNov.  temperatures get averaged, precipitation/DD/FrostDays get summed. 
- See this for the variable naming conventions. [Variables_ClimateBC.csv](https://github.com/bcgov/climR-pnw/files/8352012/Variables_ClimateBC.csv)
- gotta run but let me know if you need more clarification

**Comment by meztez** [comment]
@cmahony For Eref, do you want to use the latitude adjusted method or just the Hargreaves method directly?

https://www.researchgate.net/publication/258658989_ClimateWNA-High-Resolution_Spatial_Climate_Data_for_Western_North_America (page 20-21-22)

**Comment by cmahony** [comment]
@meztez thanks for asking!

- latitude-adjusted Eref
- Yes, RH as calculated there.

**Comment by meztez** [comment]
> @meztez thanks for asking!
> 
> * latitude-adjusted Eref
> * Yes, RH as calculated there.

Still missing a parameter S0, do you know about it?
![Screenshot from 2022-03-25 15-06-07](https://user-images.githubusercontent.com/31039074/160185745-89b12ab2-b3e9-4375-8104-f20da278683c.png)

**Comment by meztez** [comment]
I came up with tha
![Screenshot from 2022-03-25 15-24-59](https://user-images.githubusercontent.com/31039074/160188163-e6b6135d-dd9c-4578-9563-48378f4c1a4a.png)
t

**Comment by cmahony** [comment]
ha! you beat me to it! see if that works and if not we can sub in a constant for S0 and deal with it later.

**Comment by cmahony** [comment]
Closing this issue as these items are resolved and we are managing feedback as individual issues.
