### ISSUE TITLE
Access to repo

### ISSUE THREAD

**Issue by meztez** [bcgov/climR-pnw#5]
Hi @cmahony,

Can you add @meztez and @FrankBornais as contributor to this repo please.

Thanks

**Comment by cmahony** [comment]
is a write role sufficient or do you need maintain?

**Comment by cmahony** [comment]
@meztez is a write role sufficient or do you need maintain?

**Comment by meztez** [comment]
@cmahony write role is sufficient. If we need more at a later date, I'll let you know.
