### ISSUE TITLE
GCM input and output names are different after downscale()

### ISSUE THREAD

**Issue by cmahony** [bcgov/climR-pnw#50]
@meztez the hyphens in the gcm name get turned into periods in downscale(). this will be inconvenient for querying the data. 

```
> gcm <- gcm_input(
+   gcm = c("BCC-CSM2-MR"),
+   ssp = c("ssp245"),
+   period = "2041_2060",
+   max_run = 0
+ )
> results <- downscale(
+   xyz = xyz,
+   normal = normal,
+   gcm = gcm,
+   var = vars.all
+ )
> unique(results$GCM)
[1] "BCC.CSM2.MR"
```

**Comment by meztez** [comment]
The labelling in the original csv match the ouput you are seeing:

https://github.com/bcgov/climR-pnw/blob/61fe8e6c3b431cb34f3daa7fdd0c3bad7c972af0/inputs/gcmIndex.BCC-CSM2-MR.pr.csv

It is still the same as of now: 
https://github.com/bcgov/climR-pnw/blob/data/inputs_pkg/gcm/BCC-CSM2-MR/gcmIndex.BCC-CSM2-MR.pr.csv

I assumed this was done on purpose.

**Comment by cmahony** [comment]
ok yeah i had a feeling it was my mistake. so I can fix this problem by changing the csv files?

**Comment by cmahony** [comment]
sure that would be great, as long as it's not time consuming for you.

**Comment by meztez** [comment]
So, investigated. It is more than that. Both raster and terra, validate names before setting/getting them. So hyphen end up being replaced by dot. https://github.com/rspatial/raster/blob/f3dca780819f76c6949e1f34c1bf836751052d87/R/names.R#L23

I'll just gsub them in downscale

**Comment by cmahony** [comment]
issue seems to be resolved so i'm closing it. (but note the typos in the list_gcm() creating duplicates; will open a new issue for that.)

```
> list_gcm()
 [1] "ACCESS-ESM1-5" "BCC-CSM2-MR"   "CanESM5"       "CNRM-ESM2-1"   "EC-Earth3"     "GFDL-ESM4"    
 [7] "GISS-E2-1-G"   "INM-CM5-0"     "IPSL-CM6A-LR"  "MIROC6"        "MPI-ESM1-2-HR" "MPI-ESMI-2-HR"
[13] "MRI-ESM2-0"    "UKESM1-0-LL"   "UKESMI-0-LL"  
> unique(results$GCM)
 [1] "ACCESS-ESM1-5" "BCC-CSM2-MR"   "CanESM5"       "CNRM-ESM2-1"   "EC-Earth3"     "GFDL-ESM4"    
 [7] "GISS-E2-1-G"   "INM-CM5-0"     "IPSL-CM6A-LR"  "MIROC6"        "MPI-ESM1-2-HR" "MRI-ESM2-0"   
[13] "UKESM1-0-LL"  
> 
```
