### ISSUE TITLE
Observed climate for 2001-2020

### ISSUE THREAD

**Issue by cmahony** [bcgov/climR-pnw#51]
The observed 2001-2020 climate is used in many of our analyses. to get this into climR we would provide gridded anomalies in whatever grid resolution, and then modify downscale() so that it can accept these non-GCM anomalies. 
@meztez this wasn't specified in the CWU opportunity so is out of scope for this phase.

**Comment by meztez** [comment]
Maybe we should relabel normal and gcm to baseline and future.

@cmahony I think we could meetup for an hour to discuss how you want things to expand, so we label things correctly right now.

**Comment by cmahony** [comment]
sure that sounds good. are you free wednesday at 830 PST / 1230 EST?

**Comment by kdaust** [comment]
@meztez I'm going to try and add the 2001-2020 data - would you have time for a quick chat sometime to go over what would need to be done?

**Comment by meztez** [comment]
@kdaust sure

**Comment by cmahony** [comment]
steps to create the 2001-2020 anomalies using climateBC. 

1. convert the tiff dem to ascii
2. In ClimateBC/NA, choose "decadal data", then 2001-2010. 
3. choose "monthly primary variables"
4. in "input data", choose .asc instead of .csv
5. specify output and start run. 
6. repeat for 2011-2020
7. in R, create the 2001-2020 normals by taking the average of the two decades
8. calculate the anomalies by subtracting the 1961-1990 normals from the 2001-2020 (for precipitation, divide). 
9. map the anomalies to check if there is anything goofy.

**Comment by kdaust** [comment]
Now working:
`library(climRpnw)
library(data.table)
library(terra)
# Retrieve package data
data_update()

# Create a normal baseline
list_historic()
normal <- normal_input()
# # Select GCM
gcm <- gcm_input(
  gcm = c("BCC-CSM2-MR"),
  ssp = c("ssp245"),
  period = "2001_2020",
  max_run = 0
)

list_historic()
historic <- historic_input()

# Provide or create a points dataframe (lon, lat, elev)
n <- 100
xyz <- data.frame(lon = runif(n, -125, -120), lat = runif(n, 51, 53), elev = runif(n,0,500))

list_variables()
# Use downscale
results <- downscale(
  xyz = xyz,
  normal = normal,
  gcm = gcm,
  historic = historic,
  vars = c("CMD_sp","Tave_wt","PPT_sp")
)
`
