### ISSUE TITLE
expand to North America

### ISSUE THREAD

**Issue by cmahony** [bcgov/climR-pnw#52]
climR is structured nicely to scale up to North America. this would be done by: 

1. subbing in GCM files for the north american domain
2. adding a 2-4km grid of climate normals for north america, and 800m (native PRISM) normals for BC. 

This approach would allow the user to select the grid they want, or supply an 800m PRISM grid of their own in the R environment, e.g. for study areas in the US. 

@meztez let us know if you see any problems with this idea or additional considerations/steps.

**Comment by kdaust** [comment]
@cmahony once we have a climate surface for NA this should be very easy to do.

**Comment by cmahony** [comment]
ok it's on my to-do list

**Comment by cmahony** [comment]
closing this as it is redundant with a more recent issue opened by kdaust
