### ISSUE TITLE
ClimateNA produces an inferior baseline

### ISSUE THREAD

**Issue by cmahony** [bcgov/climR-pnw#55]
Using January Tmax as an example, we can see that the gradients in the mountains (eastern portion) are a bit different in ClimateNA and ClimateBC. Specifically, ClimateBC is indicating some inversions (colder valley bottom than mountain side) in the Quesnel Mountains and some other areas, which is realistic. seems that the inversions in the 800m PRISM are unresolved in the 4km ClimateNA grid. we may want to reduce our domain and use the 800m PRISM grid, or in the longer term assemble a composite grid of western North America. 

![ClimateBCvsNA Tmax01](https://user-images.githubusercontent.com/17104005/161263769-e50a1ed3-d003-4af8-84f0-defe1b95d4f1.png)

**Comment by kdaust** [comment]
I've now included the ClimateBC baseline in the package data and it seems to be working properly, so I'll close this issue for now.
