### ISSUE TITLE
ClimateBC comparisons: PAS

### ISSUE THREAD

**Issue by cmahony** [bcgov/climR-pnw#57]
@meztez Precipitation as snow doesn't seem to be working. it is zero for all months. 

![climR tests compareClimBC PAS01](https://user-images.githubusercontent.com/17104005/160638793-ffd65913-0e68-4b41-a8a9-dc26f9649f92.png)

**Comment by meztez** [comment]
Looking at the formula, the domain is constrained to 0,1. Do you then multiply the result by PPT, is it supposed to be a percentage? Any source on that would be appreciated.
![Screenshot from 2022-03-29 21-50-04](https://user-images.githubusercontent.com/31039074/160734925-fff170be-6c28-40cf-a614-da9ef0cf1dd2.png)

**Comment by meztez** [comment]
Added a multiply by PPT as it seems like the most obvious solution.

**Comment by cmahony** [comment]
@meztez yeah that is the right approach. seems like that got left out of the published equation.

**Comment by cmahony** [comment]
This took care of the bulk of the problem. there are still some discrepancies with ClimateBC, but that may be due to the blurry Tmin issue or something with the equation.
