### ISSUE TITLE
ClimateBC comparisons: Precipitation

### ISSUE THREAD

**Issue by cmahony** [bcgov/climR-pnw#58]
Precipitation seems to be working as expected with a lapse rate. However, in this case we shouldn't be using a lapse rate. in reality, precipitation doesn't vary with elevation at scales less than a couple of kilometers. ClimateBC doesn't apply a lapse rate to precipitation for this reason. the fix for this is to just to use bilinear interpolation from the baseline precipitation rasters, rather than applying a lapse rate to precipitation. @meztez, it would be great to make this modification. ideally, we would keep the option of applying a lapse rate to precipitation, perhaps with a command in the downscale() function, defaulted off. 

![climR tests compareClimBC PPT01](https://user-images.githubusercontent.com/17104005/160641268-9ffa789f-9660-4dd7-a0fe-10103e1bf733.png)

**Comment by meztez** [comment]
Added

**Comment by cmahony** [comment]
The issue seems to be resolved, so closing this issue
![climR tests compareClimBC PPT01](https://user-images.githubusercontent.com/17104005/160922783-74b7b0ac-a7bc-41a6-8239-e5849c1ccdb3.png)
