### ISSUE TITLE
Missing variables

### ISSUE THREAD

**Issue by cmahony** [bcgov/climR-pnw#59]
@meztez There are a few variables still missing from the variable set: 

- **Rad/MAR** - ignore, we're not doing radiation
- **RH** - i recall you asking about this. any issue with calculating it? 
- **MSP** - may through september precipitation. just need to sum across those months. 
- **AHM** - annual heat-moisture index - (MAT+10)/(MAP/1000)
- **DD1040** - degree-days above 10°C and below 40°C. ignore, as we don't yet have the equation for this one.  

```
# climR data
climr <- data.frame(downscale(
  xyz = xyz,
  normal = normal,
  gcm = NULL,
  var = vars.all
))

# ClimateBC data
library(data.table)
fplot=paste("C:\\Users\\CMAHONY\\OneDrive - Government of BC\\Projects\\2022_FLPapp\\inputs\\", studyarea, "_", scenario, "_", proj.year, "_MSY.csv", sep="")
Y0 <- fread(fplot, stringsAsFactors = FALSE, data.table = FALSE) #fread is faster than read.csv
Y0 <- separate(Y0, Year, into = c("GCM","scenario","proj.year"), sep = "_", remove = T)
Y0$proj.year <- gsub(".gcm","",Y0$proj.year)
Y0$proj.year <- substr(Y0$proj.year, 1,4)

climbc <- Y0[which(Y0$GCM==gcm),]

vars.missing <- names(climbc)[-c(1:8)][-which(names(climbc)[-c(1:8)]%in%names(climr)[-1])]
```
```
> vars.missing
 [1] "Rad01"  "Rad02"  "Rad03"  "Rad04"  "Rad05"  "Rad06"  "Rad07"  "Rad08"  "Rad09"  "Rad10" 
[11] "Rad11"  "Rad12"  "RH01"   "RH02"   "RH03"   "RH04"   "RH05"   "RH06"   "RH07"   "RH08"  
[21] "RH09"   "RH10"   "RH11"   "RH12"   "Rad_wt" "Rad_sp" "Rad_sm" "Rad_at" "RH_wt"  "RH_sp" 
[31] "RH_sm"  "RH_at"  "MSP"    "AHM"    "MAR"    "RH"     "DD1040"
>
```

**Comment by meztez** [comment]
MSP, AHM are typos. Fixed.
Rad/MAR I guess we are already computing it via the Hargreaves equations S0 (is it the same).
RH : I may have misinterpreted you, but I interpreted it as RH == CMI

> B: For CMI, I'm assuming this the RH variable in the appendix of the opportunity referenced paper?
> C: Yes, RH as calculated there.

So, is CMI the same as RH?

RH was not in the provided variables csv

**Comment by cmahony** [comment]
oh shoot. i misinterpreted your question. CMI is different from RH. I don't have an equation for CMI. looks like you just need to relabel CMI as RH. then i will figure out how to calculate CMI during the next development cycle.

**Comment by cmahony** [comment]
the issue seems to be resolved so i'm closing it. 

```
> vars.missing
 [1] "Rad01"  "Rad02"  "Rad03"  "Rad04"  "Rad05"  "Rad06"  "Rad07"  "Rad08"  "Rad09"  "Rad10" 
[11] "Rad11"  "Rad12"  "CMI01"  "CMI02"  "CMI03"  "CMI04"  "CMI05"  "CMI06"  "CMI07"  "CMI08" 
[21] "CMI09"  "CMI10"  "CMI11"  "CMI12"  "Rad_wt" "Rad_sp" "Rad_sm" "Rad_at" "CMI_wt" "CMI_sp"
[31] "CMI_sm" "CMI_at" "MAR"    "CMI"    "DD1040"
```
