### ISSUE TITLE
MAP (mean annual precipitation)

### ISSUE THREAD

**Issue by cmahony** [bcgov/climR-pnw#61]
the MAP for climR and ClimateBC is different. my guess is that precipitation is being averaged over the year in climR, but it should be summed over the year. [we are going with climateBC naming conventions for now, but MAP is a terrible name.]

![climR tests compareClimBC MAP](https://user-images.githubusercontent.com/17104005/160860243-f5eccbe7-419e-41a0-b194-5c2fc7aafae8.png)
]

**Comment by meztez** [comment]
They are summed over
https://github.com/bcgov/climR-pnw/blob/8c9a9bed7a561fd355e44b3ebd7f02771ffe38f0/R/append_clim_vars.R#L245

This should also be the same as PPT.

is MAP === sum(PPTi) for i in 1:12?

**Comment by cmahony** [comment]
I reloaded it and the problem seems to be resolved.
