### ISSUE TITLE
Mean warmest and coldest month temperatures

### ISSUE THREAD

**Issue by cmahony** [bcgov/climR-pnw#64]
Some of the derived variable equations aren't quite right. e.g., MWMT should be mean warmest month temperature (i.e., Tave of the month with the highest Tave for each location). currently it is calculated as annual mean Tmax. same issue for MCMT. this affects some of the downstream variables. 

`
"MWMT" = function() {set(dt, j = "MWMT", value = (v("Tmax01")+v("Tmax02")+v("Tmax03")+v("Tmax04")+v("Tmax05")+v("Tmax06")+v("Tmax07")+v("Tmax08")+v("Tmax09")+v("Tmax10")+v("Tmax11")+v("Tmax12"))/12)},
`

@meztez I'm not sure if this is straightforward to calculate since in theory the warmest month could differ among cells, and would do so at continental scales. this is perhaps something i could fix as future work, but if you have bandwidth for it that would be great.

**Comment by meztez** [comment]
so rowmax(Tave01:Tave12) = MWMT?

**Comment by cmahony** [comment]
yes, and pmin(Tave01:Tave12) = MCMT

**Comment by cmahony** [comment]
fixed

![climR tests compareClimBC MWMT](https://user-images.githubusercontent.com/17104005/161085688-e7e55f7c-2e1d-4f43-b00e-a4e6a59ed774.png)
