### ISSUE TITLE
Decimal precision

### ISSUE THREAD

**Issue by cmahony** [bcgov/climR-pnw#66]
I'm wondering if data size and speed can be improved by limiting decimal precision. don't need more than 2 decimals on temperature and 1 decimal on the other variables. just a thought. no action needed at this point

**Comment by meztez** [comment]
I've tested it, speed would not increase as bilinear interpolation, lapse rates and climate variables calculation are done with numeric types, not integer.

As for storage, it was marginal.

**Comment by cmahony** [comment]
cool.
