### ISSUE TITLE
Replicate published paper method

### ISSUE THREAD

**Issue by meztez** [bcgov/climR-pnw#8]
Main computation R interface

- [x] Define user-functions interface
- [x] Possibility utilize class dispatch to adapt to multiple input types (sf points, raster, data.frame, matrix)
- [x] Document logic steps
- [x] Quickly code a non optimized algorithm to do steps in R / Julia, anything as long as it is quick and it works.
- [x] Validate logic
- [x] Create tests to make sure logic is respected

**Comment by meztez** [comment]
Only testing remains

**Comment by cmahony** [comment]
@meztez were you able to download the desktop version of ClimateBC?
