### ISSUE TITLE
Climr r-shiny application fails

### ISSUE THREAD

**Issue by whmacken** [bcgov/climR-pnw#85]
The package ncdf4 is not specified in the package so I needed to install it manually.
The following type of error is returned when running - presumably it is not connecting properly to the server with the data.
Warning: Error in ncdf4::nc_open: Error in nc_open trying to open file ../../../climR-data/BC/tasmax_mClimMean_PRISM_historical_19710101-200

**Comment by kdaust** [comment]
The shiny application is based on some initial development work Bruno did, and not actually a climr shiny portal. Although this definitely should be done, future work.
