### ISSUE TITLE
Optimize computation performance

### ISSUE THREAD

**Issue by meztez** [bcgov/climR-pnw#9]
- [x] ~~Reimplement logic in C++ using Eigen~~
- [x] Build performance benchmarks tools
- [x] In case performance are not satisfying, evaluate alternative C++ libraries (unnecessary)
- [x] Make sure performance are similar on Windows

**Comment by meztez** [comment]
After reviewing the required computation for this project, I'm unsure we need to use Eigen.

All computation for lapse rates use low level R functions (+, -, *, ^) and are applied on large vectors without loop.

I've benchmarked against Julia and direct C++ and R is not far off, about 3-4%.

Lapse rate are simple linear regression. Here are the formula I used.

Xs are the differences in elevation between the surrounding cells and the center cell.
Ys are the differences in the target metric between the surrounding cells and the center cell.

```r
#' Simple linear regression without the intercept term
#' β = Σxy / Σx²
#' mss = Σ(xβ)², sum of squared fitted values
#' rss = Σε², sum of squared (y minus fitted), sum of absolute errors
#' R² = mss / (mss + rss)
#' Lapse rate = βR²
```

Will revisit, but so far, I do not think we need to use cpp for this.

**Comment by meztez** [comment]
@cmahony I'm trying to get a sense of performance metrics. Do you know how many points per second ClimateBC is able to process?

**Comment by cmahony** [comment]
I'm getting about 800 points/second. give it a try: [http://climatebc.ca/](http://climatebc.ca/)

**Comment by meztez** [comment]
Reopening under another as performance is very dependant on inputs format
